#-----------------
# NametagEdit v3.0
#-----------------
# Development Builds: http://ci.playmc.cc/job/NametagEdit
# Source Code: http://www.github.com/sgtcaze/NametagEdit
#-----------------

# If "true", this will remove any formatting created in the tab list by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes the tab list
TabListDisabled: false

# If enabled, this plugin will send small data MCStats.org.
MetricsEnabled: true