name: NametagEdit
main: ca.wacos.nametagedit.NametagEdit
version: 2.5.3
description: NametagEdit
authors: [wacossusca34, sgtcaze, sanjay900]
commands:
   ne:
      description: NametagEdit commands
      aliases: [nte, nametagedit]